In [3]:
#For using NumPy and to refer to an alias as 'np', you should import it by running below command. 
import numpy as np

In [5]:
#Create an array using NumPy
np.array([5,9,13])

array([ 5,  9, 13])

In [7]:
type([5,9,13])

list

In [9]:
a=np.array([5,9,13])
type(a)

numpy.ndarray

In [11]:
#Two dimension - In such array 2 square bracket is used.
a=np.array([[1,2],[3,4],[5,6]])
print("Type:",a.dtype)
print("\n",a)

Type: int32

 [[1 2]
 [3 4]
 [5 6]]


In [13]:
#dtype conversion
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [17]:
a=np.array([1,2,3],dtype=float)
print(a.dtype)

float64


In [19]:
#Convert a list to array
a=[1,2]
b=np.array(a)
print(b)
type(b)

[1 2]


numpy.ndarray

In [21]:
#Copy array into other array
c=np.asarray(b)
print(c)

[1 2]


In [23]:
#Data types
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
mat=np.array(my_mat)
print("Type/class of this object:",type(mat))
print("Here is the marks \n-------\n",mat,"\n------------\n")
print("Print dimension of this matrix:",mat.ndim)
print("Size of the matrix:",mat.size)
print("Shape of the matrix:",mat.shape)
print("Data type of the matrix:",mat.dtype)

Type/class of this object: <class 'numpy.ndarray'>
Here is the marks 
-------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
------------

Print dimension of this matrix: 2
Size of the matrix: 9
Shape of the matrix: (3, 3)
Data type of the matrix: int32


In [29]:
#arange and linespace
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [31]:
#In numpy range function also work with float number
a=np.arange(10.5,20.5,2)
print(a)

[10.5 12.5 14.5 16.5 18.5]


In [39]:
#arange in reverse order
a=np.arange(50,-1,-5)
print("Every 5th number from 50 in reverse order:",a)

Every 5th number from 50 in reverse order: [50 45 40 35 30 25 20 15 10  5  0]


In [43]:
#Linear space - in the below code we are generating 5 numbers with same distance between 10 and 40.
a=np.linspace(10,40,5)
print("Linear space from 10 to 50:",a)

Linear space from 10 to 50: [10.  17.5 25.  32.5 40. ]


In [45]:
#Include endpoints and check space between the points
#By default endpoint=True
#By default retstep=False          -retstep is used to know the distance between the numbers
a=np.linspace(2.0,3.0,num=4,endpoint=True,retstep=True) #Generate 4 numbers between 2.0 and 3.0. Also display the distance between the number (retstep)
print(a)

(array([2.        , 2.33333333, 2.66666667, 3.        ]), 0.3333333333333333)


In [47]:
#Matrix creation
print("Vector of zeros \n------------------------")
print(np.zeros(5))

Vector of zeros 
------------------------
[0. 0. 0. 0. 0.]


In [51]:
print("Vector of zeros \n------------------------")
print(np.zeros([5,6]))

Vector of zeros 
------------------------
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [53]:
#Let's create vector using ONES
print("Vector of ones \n------------------")
print(np.ones([5,6]))

Vector of ones 
------------------
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [ ]:
#Note: Above two vector of ZEROS and ONES works only for 0 and 1. It will not work with TWO, THREE etc...
#However, if you would like to create matrix of other numbers other than 0 and 1, you could use below code. Below example create a matrix of 5

In [55]:
print("Matrix of 5 \n-------------")
print(5*np.ones([5,6]))

Matrix of 5 
-------------
[[5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]]


In [61]:
#Construct diagonal matrix
x=np.arange(30)
print(x)
x=np.arange(30).reshape(5,6)    #Here generating 30 number and giving a shapre of 5 rows, 6 columns. 30=5*6 should match. reshape(5,5) will not work.
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [63]:
x=np.arange(30).reshape(2,15)
print(x)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]


In [65]:
x=np.arange(30).reshape(3,10)
print(x)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


# Random number generation
**What is random?**

numpy.random is a module in NumPy that provides tools for generating random numbers, performing random sampling, and working with various probability distributions.

numpy.random includes:
- Functions to generate random numbers
- Tools to sample from distributions (normal, binomial, Poisson, etc.)
- Methods to shuffle or permute data
- Random integers, floats, choices, etc.

**What is seed?**

numpy.seed (specifically numpy.random.seed) is a function used to set the seed for NumPy’s random number generator. This makes random outputs predictable and repeatable — crucial for debugging, testing, or reproducible research.
Random functions like np.random.rand() generate different values each time you run them. If you want the same "random" numbers every time (e.g., for consistent results), you set a seed.

**What is rand?**

The numpy.rand method is a function in NumPy used to generate random numbers from a **uniform distribution** over the interval. Dimensions of the returned array. For example, rand(2, 3) creates a 2x3 array.

Syntax: numpy.random.rand(d0, d1, ..., dn) 
- d0, d1, ..., dn: These are optional integers representing the dimensions of the array you want to create. If no arguments are provided, rand() returns a single random float.

**What is randn?**

numpy.random.randn() is a function within the NumPy library in Python that generates an array of random numbers sampled from a standard **normal distribution**. 
- Standard Normal Distribution:
This is a specific type of Gaussian distribution where the mean is 0 and the standard deviation is 1.

Syntax: numpy.random.randn(*d0, *d1, ..., *dn)
- d0, d1, ..., dn: These are optional integer arguments representing the dimensions of the desired array. If no arguments are provided, randn() returns a single float value. If positive arguments are provided, randn() generates an array of the shape (d0, d1, ..., dn). 

**What is randint?**

numpy.random.randint is a function within the NumPy library in Python used to generate random integers. It allows for the creation of either a single random integer or an array of random integers within a specified range. 

Syntax: numpy.random.randint(low, high=None, size=None, dtype=int)

In [69]:
np.random.seed(6)     #Each seed number will generate similar data. If I run this code what will be the output, if you run you will also get similar output
print("Random number generation from uniform distribution")
print(np.random.rand(10,6))

Random number generation from uniform distribution
[[0.89286015 0.33197981 0.82122912 0.04169663 0.10765668 0.59505206]
 [0.52981736 0.41880743 0.33540785 0.62251943 0.43814143 0.73588211]
 [0.51803641 0.5788586  0.6453551  0.99022427 0.8198582  0.41320093]
 [0.87626766 0.82375943 0.05447451 0.71863724 0.80217056 0.73640664]
 [0.70913175 0.54093685 0.12482417 0.9576473  0.4032563  0.21695116]
 [0.71727585 0.99420744 0.25561406 0.67130943 0.59900591 0.71733215]
 [0.93734953 0.35180977 0.2536341  0.40247251 0.74651072 0.72407057]
 [0.4061078  0.98937985 0.45049928 0.37380843 0.70962861 0.08245855]
 [0.39837292 0.77088097 0.76475098 0.28385938 0.18954219 0.47125096]
 [0.33480604 0.73473504 0.18910712 0.33110407 0.84422842 0.61502403]]


In [71]:
print("Number from normal distribution with zero mean and standard deviation 1 i.e, standard normal")
print(np.random.randn(10,6))

Number from normal distribution with zero mean and standard deviation 1 i.e, standard normal
[[-0.37550472  0.39636757 -0.47144628  2.33660781  1.50278553 -0.59545972]
 [ 0.52834106  0.9398248   0.42628539 -0.75815703 -0.16236698  0.72680996]
 [ 0.44408297 -0.85682264  0.44692842 -1.01464799 -2.1323234   0.17386307]
 [ 0.95120126  0.44189739  1.46901739  1.74951635  0.35353062 -0.64333729]
 [-0.04723705 -1.44903979 -0.03618977 -0.09084699  0.17629034  1.09462041]
 [-2.12647459  0.75144883 -0.54060704  0.79322236  0.17365335 -1.03543429]
 [ 0.87426839 -0.73957208  0.52294535 -0.59187648 -0.47748711  0.11252968]
 [ 1.90474232  0.69415315 -0.01958134  1.66284285  0.03060843 -0.29749921]
 [-0.96813764  0.16706673  0.11660197 -0.68225732 -1.91402115 -0.13990231]
 [ 0.11492459 -0.39500464 -0.95331626 -1.07282736 -0.48444561  1.36293786]]


In [75]:
print("The random integer vector:",np.random.randint(5,20,10))

The random integer vector: [ 7 17  6 19 17 19 15 14  7  5]


In [79]:
#To generate a number between 1 and 30000, create a matrix with [6,7]
print("\n Random integer matrix.")
print(np.random.randint(1,30000,(6,7)))


 Random integer matrix.
[[18780 18307 15355 11222 24641 15656  8972]
 [  599  3367 25489    10 16534 12574 19711]
 [ 7360 29664  7867  7193 14019 13020 13077]
 [18979   100 21484 21802  8255 12325  7663]
 [20160 19121 25216 16774  3611 16808  5847]
 [ 3810  3576 24615  1083 17826 26054  8618]]


In [84]:
#Geneerate OTP using randint
def Generate_OTP():
    otp=np.random.randint(1000,10000,1)
    print("Your OTP is:",otp)
    user_otp=int(input("Please enter your OTP:"))
    if user_otp==otp:
        print("Login successful!")
    else:
        print("Please enter correct OTP.")

Generate_OTP()

Your OTP is: [4292]


Please enter your OTP: 4292


Login successful!


In [86]:
emp_salary=np.random.randint(8,70,10)
print(emp_salary)

[21 37 10 26 19 28 50 66 48 47]


In [88]:
#Set minimum and maximum salary using a_min and a_max
np.clip(emp_salary,a_min=20,a_max=50)  #If we use clip method, all maximum and minimum value we can set as per our use. 
#Here, number between 20/50 to display and any number which is less than 20 will be displayed as 20 | any number which more than 50 will be displayed as 50

array([21, 37, 20, 26, 20, 28, 50, 50, 48, 47])

In [5]:
#Use where statement for finding a value based on criteria
import numpy as np
emp_salary=np.random.randint(8,70,10)
print(emp_salary)
print(np.where(emp_salary <25))   #It gives you the index number of the output from left to right.

[ 8 43 64 51 62 39 69 22 64 37]
(array([0, 7], dtype=int64),)


In [9]:
#To check the actual value by using index by using double square brackets [[ ]]
emp_salary[[0,7]]

array([ 8, 22])

In [ ]:
#Similarly we can check any conditions (<,>,=,=>,<=)

In [13]:
#How to use alias for randint
import numpy as np
from numpy.random import randint as ri

In [15]:
a=ri(1,99,30)
print(a)

[27 90 89 64 49 17 68 71 81  4  2 49 61 59 88  3  4 23 20 29 24 56  5 40
 32 19  4  9 84  2]


In [19]:
b=a.reshape(2,3,5)   #It creates 2 matrix, 3 rows and 5 columns
print(b)

[[[27 90 89 64 49]
  [17 68 71 81  4]
  [ 2 49 61 59 88]]

 [[ 3  4 23 20 29]
  [24 56  5 40 32]
  [19  4  9 84  2]]]


In [21]:
c=a.reshape(6,5)
print(c)

[[27 90 89 64 49]
 [17 68 71 81  4]
 [ 2 49 61 59 88]
 [ 3  4 23 20 29]
 [24 56  5 40 32]
 [19  4  9 84  2]]


In [25]:
print("Minimum of a is:",c.min())
print("Maximum of a is:",c.max())

Minimum of a is: 2
Maximum of a is: 90


In [27]:
#Sorting
m=ri(1,100,25).reshape(5,5)   #Creating matrix of integer
print("\n 5 x 5 matrix of random integer: \n", "-"*50,"\n",m)
print("\n Here is the sorted matrix along each row: \n", "-"*50,"\n",np.sort(m))   #default axis=1
print("\n Here is the sorted matrix along each column: \n","-"*50,"\n",np.sort(m,axis=0))


 5 x 5 matrix of random integer: 
 -------------------------------------------------- 
 [[65 52 48 68 76]
 [39 10 78 54 57]
 [55 10 92 90 54]
 [98 53 47 47 22]
 [74 59 97 70 19]]

 Here is the sorted matrix along each row: 
 -------------------------------------------------- 
 [[48 52 65 68 76]
 [10 39 54 57 78]
 [10 54 55 90 92]
 [22 47 47 53 98]
 [19 59 70 74 97]]

 Here is the sorted matrix along each column: 
 -------------------------------------------------- 
 [[39 10 47 47 19]
 [55 10 48 54 22]
 [65 52 78 68 54]
 [74 53 92 70 57]
 [98 59 97 90 76]]


In [29]:
#Index and slicing
arr=np.arange(13,30)
print("Array:",arr)

Array: [13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [31]:
print("Print 7th index of Array:",arr[7])

Print 7th index of Array: 20


In [35]:
print("Element of 3rd and 5th index is:",arr[3:5])

Element of 3rd and 5th index is: [16 17]


In [37]:
print("Elements from 4th to end is:",arr[4:])

Elements from 4th to end is: [17 18 19 20 21 22 23 24 25 26 27 28 29]


In [39]:
#Save arr in abc and check from 4th to last index values
abc=arr[4:]
print(abc)

[17 18 19 20 21 22 23 24 25 26 27 28 29]


In [41]:
print("Elements from last backwards:",abc[-1::-2])   #last index=-1 to first index with step size as -2

Elements from last backwards: [29 27 25 23 21 19 17]


In [43]:
print("7th element from las backwards are:",abc[-1:-8:-1])

7th element from las backwards are: [29 28 27 26 25 24 23]


In [47]:
print("Elements at 2nd 4th and 9th index are:",arr[[2,4,9]])   #Pass a list as a index to subset

Elements at 2nd 4th and 9th index are: [15 17 22]


In [13]:
import numpy as np
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
mat=np.array(my_mat)
print(mat)
print("Entire row at index 2: \n",mat[2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Entire row at index 2: 
 [7 8 9]


In [15]:
print("Entire row at index 2: \n",mat[0:2])

Entire row at index 2: 
 [[1 2 3]
 [4 5 6]]


In [17]:
print("Entire row at index 2: \n",mat[0:2,1])    #0:2= 0th row to 1st row | start from 1st index in column

Entire row at index 2: 
 [2 5]


In [19]:
print("Entire row at specific index: \n",mat[0:2,0:2])

Entire row at specific index: 
 [[1 2]
 [4 5]]


In [11]:
print("Entire column at index 3:\n",mat[:,1:])

Entire column at index 3:
 [[2 3]
 [5 6]
 [8 9]]


In [21]:
print("Matrics with indices 1 and 2:\n",mat[1:2,1:2])

Matrics with indices 1 and 2:
 [[5]]


In [23]:
print(mat[0:2,[1,2]])   #[1,2] - it selects values of the column 1 and 2

[[2 3]
 [5 6]]


In [25]:
#Updating matrix

mat[0,2]=200   #0th row and 2nd column to be replaced with 200. 3 will be replaced with 200.
print(mat)

[[  1   2 200]
 [  4   5   6]
 [  7   8   9]]


In [27]:
mat[1,0]=100    #1st row and 0th column to be replaced with 100. 4 will be replaced with 100.
print(mat)

[[  1   2 200]
 [100   5   6]
 [  7   8   9]]


In [31]:
import numpy as np
from numpy.random import randint as ri
mat=np.array(ri(10,100,15).reshape(3,5))
print("Matrix of random 2 digit numbers:\n",mat)

Matrix of random 2 digit numbers:
 [[28 18 60 52 45]
 [58 30 90 39 89]
 [97 44 21 81 17]]


In [33]:
print("Elements greater than 50:\n",mat[mat>50])   

Elements greater than 50:
 [60 52 58 90 89 97 81]


In [37]:
#if we wrote [mat>50] instead of mat[mat>50], we will get boolean values. Let's see
print("Elements greater than 50:\n",mat>50) 

Elements greater than 50:
 [[False False  True  True False]
 [ True False  True False  True]
 [ True False False  True False]]


In [13]:
import numpy as np
from numpy.random import randint as ri
mat=np.array(ri(10,100,15).reshape(3,5))
print(mat)
print(np.where(mat==84))

[[96 23 31 21 21]
 [78 87 94 47 48]
 [17 45 52 45 51]]
(array([], dtype=int64), array([], dtype=int64))
