# Subsetting
When we want to fetch only few data from matrix

In [7]:
import numpy as np
from numpy.random import randint as ri

# Create 2 dimensional matrix
mat=np.array(ri(10,100,15)).reshape(3,5)
print(mat)

[[44 77 30 17 50]
 [47 93 89 44 55]
 [93 59 89 94 81]]


In [3]:
# Create 3 dimensional matrix
mat=np.array(ri(10,100,30)).reshape(2,3,5)    #2 means - it will create 2 matrixes. 2 is depth, 3 is row and 5 is column
print(mat)

[[[14 71 20 54 69]
  [61 69 37 76 77]
  [96 46 58 46 41]]

 [[19 20 85 66 84]
  [50 48 75 46 34]
  [46 65 20 69 61]]]


# Universal functions

In [9]:
mat1=np.array(ri(1,10,9)).reshape(3,3)
mat2=np.array(ri(1,10,9)).reshape(3,3)
print("First matrix of single digit number:\n",mat1)
print("Second matrix of single digit number:\n",mat2)

First matrix of single digit number:
 [[3 1 4]
 [6 6 2]
 [5 8 9]]
Second matrix of single digit number:
 [[9 6 5]
 [1 3 5]
 [5 2 9]]


In [11]:
print("Division of matrix:\n",mat1/mat2)

Division of matrix:
 [[0.33333333 0.16666667 0.8       ]
 [6.         2.         0.4       ]
 [1.         4.         1.        ]]


In [17]:
mat1=np.array(ri(1,10,9)).reshape(3,3)
mat2=np.array(ri(1,10,9)).reshape(3,3)
print("Mat1:\n",mat1)
print("Mat2:\n",mat2)
print("Linear combination: 3*mat1 - 2*mat2:\n",3*mat1-2*mat2)

Mat1:
 [[4 4 5]
 [2 5 4]
 [8 8 4]]
Mat2:
 [[6 3 8]
 [5 8 3]
 [2 8 4]]
Linear combination: 3*mat1 - 2*mat2:
 [[ 0  6 -1]
 [-4 -1  6]
 [20  8  4]]


# Broadcasting

Numpy operations are usually dont on pairs of arrays on an element by element basis. in the simplest case, the two arays must have exactly the same shape. Numpy broadcasting rules relaxex this constraints when the array shape meet certain constraints when operatings on two array, Numpy compares their shape element wise it starts with the trailing dimensions, and word its way forword, two dimension are compatible #when they are eqaul, or one of them is 1.

In [22]:
start=np.zeros((3,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [24]:
# Create a rank1 ndarray with 3 values
add_rows=np.array([[1,0,2]])
print(add_rows)

[[1 0 2]]


In [26]:
add_rows=np.array([[1,0,2]])
print(add_rows)

[[1 0 2]]


In [30]:
y=start+add_rows    #adds to each row of start using broadcasting
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [34]:
# Transpose

add_col=np.array([[0,2,2,3]])
print(add_col)

[[0 2 2 3]]


In [36]:
add_col=add_col.T     # By using 'T' we are transposing from row to column and vice versa.
print(add_col)

[[0]
 [2]
 [2]
 [3]]


## Array math

In [48]:
mat1=np.array(ri(1,10,9)).reshape(3,3)
mat2=np.array(ri(1,10,9)).reshape(3,3)
print("\n 1st matrix of random single digit number\n----------------------------------\n",mat1)
print("\n 2nd matrix of random single digit number\n----------------------------------\n",mat2)

print("\n Square root of 1st matrix using np:\n","-"*50,"\n",np.sqrt(mat1))
print("\n Square of 2nd matrix using np:\n","-"*50,"\n",np.square(mat2))


 1st matrix of random single digit number
----------------------------------
 [[3 1 6]
 [9 2 3]
 [5 8 7]]

 2nd matrix of random single digit number
----------------------------------
 [[3 3 6]
 [1 1 5]
 [4 7 9]]

 Square root of 1st matrix using np:
 -------------------------------------------------- 
 [[1.73205081 1.         2.44948974]
 [3.         1.41421356 1.73205081]
 [2.23606798 2.82842712 2.64575131]]

 Square of 2nd matrix using np:
 -------------------------------------------------- 
 [[ 9  9 36]
 [ 1  1 25]
 [16 49 81]]


In [ ]:
### It is advised to practice more functions of matrix to matrix

# Math Library

In [51]:
# Addition
a=5
b=3
addition=a+b
print("Addition:",addition)

Addition: 8


In [54]:
# Subtraction
sub=a-b
print("Subration:",sub)

Subration: 2


In [56]:
# Multiplication
mult=a*b
print("Multiplication:",mult)

Multiplication: 15


In [64]:
import math

# Round to nearest integer
num=5.5
rounded=round(num)   # It rounds to 5 if it is 5.4 but it will round to 6 if it is 5.5 and above.
print(rounded)

# Round down
rounded_down=math.floor(num)
print(rounded_down)

# Round up
rounded_up=math.ceil(num)
print(rounded_up)

6
5
6


# Logarithm

NumPy provides functions to calculate logarithms with different bases, primarily natural logarithm (base e), base 2, and base 10.

Basic formula: log_b(x)=y   means, b^y=x

b= base
x= result
y= power/exponent
log_b(x)= logarithm of x with base b

**what is base?**

In logarithms, the base refers to the number that is raised to a power to obtain the argument of the logarithm. For example, in the expression \(\log _{b}(x)\), \(b\) is the base. This means that \(b\) raised to the power of \(\log _{b}(x)\) equals \(x\).

#### Example 1

log10(1000) = ?
This means, how many times 10 to multiply so that we get 1000.
Answer: 1og10(1000)=3

#### Example 2

If no base is written then default base is 10 to consider.
Answer: log(100)=log10(100)=2

#### Example 3

log2(8)=?
Base=2, Result=8
Answer: log2(8)=3

#### Practice Questions:

log10(10000)=4
log2(16)=4
log(1)=0
log5(25)=2

In [2]:
import math

# Natural logarithm
num=8
natural_log=math.log(num)
print("Natural logarithm:",natural_log)

# Base-10 logarithm
base_10_log=math.log10(num)
print("Base 10 logarithm:",base_10_log)

# Base-2 logarithm
base_2_log=math.log2(num)
print("Base 2 logarithm:",base_2_log)

#### NOTE: Python doesn't understand any other number as base other than 2 and 10. If we would like to write log5(x) - it's invalid for python.

Natural logarithm: 2.0794415416798357
Base 10 logarithm: 0.9030899869919435
Base 2 logarithm: 3.0


In [6]:
num=float(input("Please enter a number to calucate it's base-5 logarithm:"))

# Base-5 logarithm using math.log(x, base)
log_base_5=math.log(num, 5)
print("Base_5 logarithm:",log_base_5)

Please enter a number to calucate it's base-5 logarithm: 125


Base_5 logarithm: 3.0000000000000004


### Normal Mathematical Operators

In [10]:
# / normal division
print(5/2)   # Output=2.5

2.5


In [12]:
# floor division
print(5//2)   # Output=2

2


In [14]:
# Modulus operator
print(5%2)   # Output=1

1


### Questions on Summation in Python

#### Sum of a list

**Question:** Given a list numbers=[1,2,3,4,5], what will be the total sum using sum() function?
- Hint: Use sum(numbers) to calculate the sum
- 
#### Sum of First N natural numbers

**Question:** For n=10, calculate the sum of n natural number using the formula n*(n+1)//2

#### Sum using Loop

**Question:** Using a loop, find the sum of elements in the list numbers=[1,2,3,4,5] by initializing a vairable total=0 and adding each number


In [7]:
# Sum of a list
numbers=[1,2,3,4,5]
a=sum(numbers)
print("Sum of a list is:",a)

# Sum of First N natural numbers
n=10
a=n*(n+1)//2
print("Sum of first",n,"numbers is:",a)

# Sum using Loop
numbers=[1,2,3,4,5]
total=0
for num in numbers:
    total =total+num
print("Sum of a list using loop is:", total)

Sum of a list is: 15
Sum of first 10 numbers is: 55
Sum of a list using loop is: 15


#### Product of a list

**Question:** Given a list numbers=[1,2,3,4,5], what will be the product of all elements using the math.prod() function?
- Hint: use math.prod(numbers)

#### Product using loop

**Question:** Usin a loop, find the product of elements in the list numbers=[1,2,3,4,5] by initializing product_loop=1 and multiplying each number
- Hint: Use a for loop with product_loop *=num

#### Product of first N natural numbers (Factorial)

**Question:** For n=5, calculate the factorial (product of n natural numbers) using the math.factorial() function.
- Hint: Use math.factorial(n) to complete the factorial

In [14]:
# Product of a list
import math
numbers=[1,2,3,4,5]
a=math.prod(numbers)
print("Product of a list numbers is:",a)

# Product using loop
numbers=[1,2,3,4,5]
product_loop=1
for num in numbers:
    product_loop *=num
print("Product using loop is:",product_loop)

# Product of first N natural numbers (Factorial)
n=5
a=math.factorial(n)
print("Product of first 5 natural numbers is:",a)

Product of a list numbers is: 120
Product using loop is: 120
Product of first 5 natural numbers is: 120


## Questions on different calculation in python

#### Difference between two numbers

**Question:** Given a=10 and b=7, what will be the difference between consecutive elements using a list comprehension.

- Hint: Use a - b to calculate the difference.

#### Difference in a list

**Question:** For a list numbers=[10,20,30,40], calculate the difference between the elements using a list comprehension.

- Hint: Using zip(numbers[:-1], numbers[1:]) with j-i to find difference

#### Absolute difference

**Question:** Find the absolute difference of two numbers by using abs() function.

- Hint: Use abs(num1-num2)


In [18]:
# Difference between two numbers
a=10
b=7
diff=a-b
print("The difference between a and b is:",diff)

# Difference in a list
numbers=[10,20,30,40]
diff= [j-i for i, j in zip(numbers[:-1],numbers[1:])]
print("Difference in a list:",diff)

# Absolute difference
diff= abs(a-b)
print("Absolute difference of a and b is:",diff)

The difference between a and b is: 3
Difference in a list: [10, 10, 10]
Absolute difference of a and b is: 3


# Greatest Common Divisor (GCD)

**Definition:** The greatest common divisor (GCD), also known as the highest common factor (HCF), of two integers can be calculated in Python using several methods. The most straightforward and efficient approach is to utilize the built-in math.gcd() function.

**Example:**
GCD of 12 and 15

Factors of 12: 1,2,3,4,6,12
Factors of 15: 1,3,5,15

Common factors: 1,3
Highest common factor (HCF)=3

In [21]:
# Example of GCD
import math
a=math.gcd(12,15)
print(a)

3


In [37]:
# GCD of a list of numbers using a function
def gcd_num(numbers):
    gcd=numbers[0]
    for num in numbers[1:]:
        gcd=math.gcd(gcd,num)
    return gcd
numbers=[4,16,48]
gcd_numbers=gcd_num(numbers)
print("GCD of a list of numbers is:",gcd_numbers)

GCD of a list of numbers is: 4


# Least Common Multiple 

**Definition:** It refers to the smallest positive integer that is a multiple of two or more given integers. For example, the LCM of 4 and 6 is 12, as 12 is the smallest number that can be divided by both 4 and 6 without a remainder.

**Example:** LCM of 4 and 5
Multiples of 4: 4,8,12,16,20,..
Multiples of 5: 5,10,15,20,25,..

First common multiple of 4 and 5 is: 20
LCM(4,5)=20

#### LCM of two numbers

**Question:** Given a=12 and b=15, calculate the LCM using formula abs(a*b)//math.gcd(a,b)
- Hint: Use math.gcd() to find GCD and apply the LCM formula

#### LCM of a list of numbers

**Question:** For a list numbers=[4,5,6], write a function lcm_list() to calculate the LCM of all numbers in the list using a loop and math.gcd().
- Hint: Initialize LCM with the first number and iteratively update it with lcm * num // math.gcd(lcm, num) for each subsequent number.


In [29]:
# LCM of two numbers
import math
a=12
b=15
c=abs(a*b) // math.gcd(a,b)
print("LCM of",a,"and",b,"is:",c)

# LCM of a list of numbers
def list_numbers(numbers):
    lcm=numbers[0]
    for num in numbers[1:]:
        print(lcm)
        lcm=lcm*num//math.gcd(lcm,num)
    return lcm
numbers=[4,5,6]
lcm_numbers=list_numbers(numbers)
print("LCM of a list of numbers:",lcm_numbers)

LCM of 12 and 15 is: 60
4
20
LCM of a list of numbers: 60


### Set operations in python

In [40]:
# Union of sets
set1={1,2,3}
set2={3,4,5}
union_set=set1.union(set2)
print("Union of set:",union_set)

# Intersection of sets
int_sec=set1.intersection(set2)
print("Intersection of sets:",int_sec)

# Difference of sets
diff_sets=set1.difference(set2)       #What is there in set1, it is not there in set2
print("Difference of sets:",diff_sets)

Union of set: {1, 2, 3, 4, 5}
Intersection of sets: {3}
Difference of sets: {1, 2}


## Trigonometric Fuctions in Python

#### Sine of an angle

**Question:** Given an angle of 30 degrees, calculate it's sine using the math.sin() function.
- Hint: First convert degrees to radians using math.radians(), then apply math.sin().

#### Cosine of an angle

**Question:** Using the same of 30 degrees, compute the cosine using math.cos() function.
- Hint: Make sure to convert the angle to radians before using math.cos()

#### Tangent of an angle

**Question:** Find the tangent of 30 degrees using the math.tan() function.
- Hint: Convert the angle to radians using math.radians() before applying math.tan()

In [43]:
import math

# Sine function
angle=math.radians(30)
sine=math.sin(angle)
print("Sine of 30 degrees:",sine)

# Cosine function
cosine=math.cos(angle)
print("Cosine of 30 degrees:",cosine)

# Tangent function
tangent=math.tan(angle)
print("Tangent of 30 degrees:",tangent)

Sine of 30 degrees: 0.49999999999999994
Cosine of 30 degrees: 0.8660254037844387
Tangent of 30 degrees: 0.5773502691896257
